### ISSUE TITLE
Handle file not found errors properly

### ISSUE THREAD

**Issue by Angelmmiguel** [Angelmmiguel/fu#32]
Now, if a non existing file is passed to the CLI, it shows a generic rust message:

```
$ fu ./not-exist
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

Instead, we should show a proper message using the red color.

**Comment by kseistrup** [comment]
Did it really make it to the 1.0.0 release?

I am completely new to `fu`: I downloaded the Linux binary from the release page and decided to tally my home directory:

```sh
$ fu .
No such file or directory (os error 2)
$ fu --version
fu 1.0.0 - Git commit: 2b9e0951b854f153c31b4329c718e63459173a87
```

It is not so much that it aborts on a missing file or directory, as it is an unhelpful error message: Of the thousands and thousands of files and directories in my home directory, apparently there is a dangling symbolic link somewhere. But where is it? A file or directory name would have helped tremendously.

Kudos for putting the git commit in the version string. :1st_place_medal: 

/cc [ Git commit: 2b9e0951b854f153c31b4329c718e63459173a87 ]
