### ISSUE TITLE
windows tar.gz it's just a .tar instead

### ISSUE THREAD

**Issue by Slach** [Angelmmiguel/fu#40]
I tried to add `fu` as https://scoop.sh package to install under windows,
unfortunately
https://github.com/Angelmmiguel/fu/releases/download/1.0.0/fu-x86_64-pc-windows-gnu.tar.gz
this is a just .tar instead of gzipped tar

**Comment by Slach** [comment]
looks like you manually prepare your /releases pages? i don't see any github actions for it

**Comment by Angelmmiguel** [comment]
Hello @Slach!

Yes, automation is still a pending task for this project. The v1.0.0 release was manually generated and I missed the `gzip` part when bundling the Windows version. I will update that file this evening and will let you know when it's done. It's amazing you're adding it to scoop!

Thank you 😄

**Comment by Slach** [comment]
file still tar instead of tar.gz
any progress?

**Comment by Angelmmiguel** [comment]
Hello @Slach!

Sorry for the delay here, I miss this issue in my todo list 😞. Today, I'm going to add the automations to release new versions from GitHub Actions. I will try to include `aarch64` builds too.

**Comment by Angelmmiguel** [comment]
@Slach I just merged the changes and released a new v1.0.1 version: https://github.com/Angelmmiguel/fu/releases/tag/v1.0.1. Now, the process is fully automated so newer versions shouldn't miss the gzip part during compilation 😄 

Please, ping me if you need any other change to integrate it with https://scoop.sh.

**Comment by Slach** [comment]
Ok. let's wait when PR to scoop merge
https://github.com/ScoopInstaller/Main/pull/4396

**Comment by Angelmmiguel** [comment]
Oh! I saw the Scoop requirementes @Slach. Let's see if the tool gets enough traction to reach those numbers :)

**Comment by Angelmmiguel** [comment]
> [ScoopInstaller/Extras#10363](https://github.com/ScoopInstaller/Extras/pull/10363) merged please update your Readme with following instuctions
> 
> ```
> scoop bucket add extras
> scoop install fu
> ```

Done! I also added your contribution to the acknowledgements section.

Thank you @Slach 😄
